# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f496094a090c4be30f9b872c061b62d5f529360d9b36130b99c61006cc102e53608b13d2f9c19099810a37555c214c54c27289c9fb2a21c5a953b818232986d

test:
  secret_key_base: 410e16f98047eb9be497bd4b9cd1c2b06b96c8ac5e2d2df1613d0a9efce0dc0cfe617295519c8092cf33822a4934e0dfc6325ffbff8990fbf5c13ec9ca893e2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
